"""Quiz Prompts - Templates para geracao de questoes."""

from .templates import (
    DEFAULT_DIFFICULTY_DISTRIBUTION,
    FIRST_QUESTION_FALLBACK,
    FIRST_QUESTION_PROMPT,
    QUIZ_GENERATION_PROMPT,
    QUIZ_SYSTEM_PROMPT,
    SINGLE_QUESTION_PROMPT,
    TOPIC_KEYWORDS,
)

__all__ = [
    "QUIZ_GENERATION_PROMPT",
    "SINGLE_QUESTION_PROMPT",
    "FIRST_QUESTION_PROMPT",
    "FIRST_QUESTION_FALLBACK",
    "TOPIC_KEYWORDS",
    "QUIZ_SYSTEM_PROMPT",
    "DEFAULT_DIFFICULTY_DISTRIBUTION",
]
